version: "3.7"

services:
  roadmap:
    container_name: roadmap
    image: node:18-bullseye-slim
    command: npm run debug

    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 13050:1234