version: "3.7"

services:
  roadmap:
    container_name: roadmap
    # image: node:18-bullseye-slim
    image: roadmap
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run prod
    # user: "1004:1001"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 13050:13048